//AddWatchWindowVars Lab 4
expRemoveAll()
//Variables
expAdd ("CLLLC_Lab.CLLLC_Lab_Enum",getNatural())
expAdd ("CLLLC_pwmSwState.CLLLC_PwmSwState_Enum",getNatural())
expAdd ("CLLLC_powerFlowState.CLLLC_PowerFlowState_Enum",getNatural())
expAdd ("CLLLC_tripFlag.CLLLC_TripFlag_Enum", getNatural())
expAdd ("CLLLC_clearTrip",getNatural())
expAdd ("CLLLC_closeGiLoop",getNatural())
expAdd ("CLLLC_iSecRef_Amps",getNatural())
expAdd ("CLLLC_iSecSensed_Amps",getNatural())
expAdd ("CLLLC_vPrimSensed_Volts",getNatural())
expAdd ("CLLLC_iPrimSensed_Amps",getNatural())
expAdd ("CLLLC_vSecSensed_Volts",getNatural())
expAdd ("CLLLC_pwmPhaseShiftPrimSecRef_ns",getNatural())
expAdd ("CLLLC_pwmDeadBandREDPrimRef_ns",getNatural())
expAdd ("CLLLC_pwmDeadBandFEDPrimRef_ns",getNatural())
expAdd ("CLLLC_pwmFrequency_Hz", getNatural())
expAdd ("EPwm1Regs.TZFLG",getNatural())
